version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    logging:
      driver: 'json-file'
      options:
        max-file: '1'
        max-size: '10m'
    restart: unless-stopped
    networks:
      - rede-default

    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api-receitinhas:
    image: cledsonv/receitinhas
    container_name: api
    restart: always
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      GOOGLE_APPLICATION_CREDENTIALS: src/main/resources/adc.json
      BUCKET_CONFIG: ${BUCKET_CONFIG}
      LOG_LEVEL: ${LOG_LEVEL}
      OTEL_LOG_LEVEL: ${LOG_LEVEL}
      OTEL_RESOURCE_ATTRIBUTES: deployment.environment=test
      OTEL_EXPORTER_OTLP_ENDPOINT: http://lucas1:4318
    entrypoint:
      [
        'java',
        '-javaagent:/app/opentelemetry-javaagent.jar',
        '-jar',
        'application.jar'
      ]
    logging:
      driver: 'json-file'
      options:
        max-file: '1'
        max-size: '10m'
    volumes:
      - ./opentelemetry-javaagent.jar:/app/opentelemetry-javaagent.jar
      - ./config:/src/main/resources/config
      - ./chave_privada_perfil_oracle.pem:/src/main/resources/chave_privada_perfil_oracle.pem
    networks:
      - rede-default
    ports:
      - "80:80"
  cache:
    image: redis:6.2.16-alpine
    container_name: cache
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20
    logging:
      driver: 'json-file'
      options:
        max-file: '1'
        max-size: '10m'
    networks:
      - rede-default
    volumes:
      - cache:/data
networks:
  rede-default:


volumes:
  pgdata:
  cache:
    driver: local